const en = {
    welcome: "Welcome",
    login: "Sign In",
    signup: "Sign Up",
    email: "Email",
    password: "Password",
    confirmPassword: "Confirm Password",
    verify: "Verify code",
    resend: "Resend code in 60 s",
    description: "Find food & fun spots that match your vibe – no stress, just tap!",
    invalid_email: "Invalid email address",
    invalid_password: "Password must be at least 8 characters",
    forgot_password: "Forgot Password?",
    password_mismatch: "Passwords do not match",
    continue: "Continue",
    sending: "Sending...",
    verifying: "Verifying...",
    enter_email_placeholder: 'Enter your email address',
    enter_password_placeholder: 'Enter your password',
    enter_confirm_password_placeholder: 'Confirm your password',
    search: 'Search',
    login_description: 'Sign in to your account',
    signup_description: 'Create your account',
    or: 'Or',
    google_signin: 'Sign in with Google',
    google_signup: 'Sign up with Google',
    already_have_account: 'Already have an account?',
    dont_have_account: "Don't have an account?",
    sign_in: 'Sign In',
    sign_up: 'Sign Up',
    // OTP related
    otp_sent: 'OTP sent to your email. Please verify within 6 minutes.',
    enter_otp: 'Enter OTP',
    verify_otp: 'Verify OTP',
    resend_otp: 'Resend OTP',
    otp_expires_in: 'OTP expires in',
    seconds: 'seconds',
    // Registration
    registration_success: 'Registration completed successfully',
    // Error messages
    login_failed: 'Login failed. Please check your credentials.',
    signup_failed: 'Signup failed. Please try again.',
    network_error: 'Network error. Please check your connection.',
    // Success messages
    login_success: 'Login successful',
    signup_success: 'Account created successfully',
    // Forgot password
    forgot_password_description: 'Enter your email address and we\'ll send you a reset code',
    send_reset_code: 'Send Reset Code',
    back_to_login: 'Back to Login',
    enter_email: 'Enter your email',
    hengout: 'Hengout',
    reset_password: 'Reset Password',
    enter_new_password: 'Enter your new password',
    resetting: 'Resetting...',
    back_to_verification: 'Back to Verification',
    dont_receive_code: 'Didn\'t receive the code?',
    new_password: 'New password',
    confirm_new_password: 'Confirm new password',

    // Profile
    setup_profile: 'Setup Profile',
    setup_profile_description: 'Complete your profile to get started',
    display_name: 'Display Name',
    enter_display_name: 'Enter your display name',
    gender: 'Gender',
    male: 'Male',
    female: 'Female',
    other: 'Other',
    profile_setup_info: 'You can update your profile information later in settings',
    initializing: 'Initializing...',
    complete_setup: 'Complete Setup',
    skip_for_now: 'Skip for now',
};
export default en; 