const vi = {
    welcome: "Chào mừng",
    login: "Đăng nhập",
    signup: "Đăng ký",
    email: "Email",
    password: "Mật khẩu",
    confirmPassword: "Xác nhận mật khẩu",
    verify: "Xác minh mã",
    resend: "Gửi lại mã sau 60 giây",
    description: "Khám phá chỗ ăn chơi theo gu cá nhân – không cần nghĩ nhiều, chỉ cần mở app!",
    invalid_email: "Địa chỉ email không hợp lệ",
    invalid_password: "Mật khẩu phải có ít nhất 8 ký tự",
    forgot_password: "Quên mật khẩu?",
    password_mismatch: "Mật khẩu không khớp",
    continue: "Tiếp tục",
    sending: "Đang gửi...",
    verifying: "Đang xác minh...",
    enter_email_placeholder: 'Nhập địa chỉ email',
    enter_password_placeholder: 'Nhập mật khẩu',
    enter_confirm_password_placeholder: 'Xác nhận mật khẩu',
    search: 'Tìm kiếm',
    login_description: 'Đăng nhập vào tài khoản của bạn',
    signup_description: 'Tạo tài khoản mới',
    or: 'Hoặc',
    google_signin: 'Đăng nhập bằng Google',
    google_signup: 'Đăng ký bằng Google',
    already_have_account: 'Đã có tài khoản?',
    dont_have_account: "Chưa có tài khoản?",
    sign_in: 'Đăng nhập',
    sign_up: 'Đăng ký',
    // OTP related
    otp_sent: 'OTP đã được gửi đến email của bạn. Vui lòng xác minh trong vòng 6 phút.',
    enter_otp: 'Nhập OTP',
    verify_otp: 'Xác minh OTP',
    resend_otp: 'Gửi lại OTP',
    otp_expires_in: 'OTP hết hạn sau',
    seconds: 'giây',
    // Registration
    registration_success: 'Đăng ký thành công',
    // Error messages
    login_failed: 'Đăng nhập thất bại. Vui lòng kiểm tra thông tin đăng nhập.',
    signup_failed: 'Đăng ký thất bại. Vui lòng thử lại.',
    network_error: 'Lỗi mạng. Vui lòng kiểm tra kết nối.',
    // Success messages
    login_success: 'Đăng nhập thành công',
    signup_success: 'Tạo tài khoản thành công',
    // Forgot password
    forgot_password_description: 'Nhập địa chỉ email và chúng tôi sẽ gửi mã đặt lại',
    send_reset_code: 'Gửi Mã Đặt Lại',
    back_to_login: 'Quay Lại Đăng Nhập',
    enter_email: 'Nhập email của bạn',
    hengout: 'Hengout',
    reset_password: 'Đặt Lại Mật Khẩu',
    enter_new_password: 'Nhập mật khẩu mới của bạn',
    resetting: 'Đang đặt lại...',
    back_to_verification: 'Quay Lại Xác Minh',
    dont_receive_code: 'Không nhận được mã?',
    new_password: 'Mật khẩu mới',
    confirm_new_password: 'Xác nhận mật khẩu mới',

    // Profile
    setup_profile: 'Thiết lập hồ sơ',
    setup_profile_description: 'Hoàn thiện hồ sơ để bắt đầu',
    display_name: 'Tên hiển thị',
    enter_display_name: 'Nhập tên hiển thị của bạn',
    gender: 'Giới tính',
    male: 'Nam',
    female: 'Nữ',
    other: 'Khác',
    profile_setup_info: 'Bạn có thể cập nhật thông tin hồ sơ sau trong cài đặt',
    initializing: 'Đang khởi tạo...',
    complete_setup: 'Hoàn tất thiết lập',
    skip_for_now: 'Bỏ qua bây giờ',
};
export default vi; 